### ISSUE TITLE
Google Chrome virus has been detected

### ISSUE THREAD

**Issue by sokolinivan** [agejevasv/goradion#1]
When downloading from releases on Windows, Google Chrome gives an error with a message that a virus has been detected in the file. What is it? What could it be cussing at in this context?

![image](https://github.com/agejevasv/goradion/assets/7392926/98e17b19-4654-4663-a387-6060ae99d0a9)

**Comment by sokolinivan** [comment]
Which is funny with the 386 there is no such problem)

**Comment by agejevasv** [comment]
Interesting, all the files are built on GitHub via GitHub Actions. A false positive maybe?

**Comment by sokolinivan** [comment]
Maybe. It's weird. I built it from source, it's fine.

**Comment by agejevasv** [comment]
Could be this issue: https://go.dev/doc/faq#virus

> **Why does my virus-scanning software think my Go distribution or compiled binary is infected?**
>
> This is a common occurrence, especially on Windows machines, and is almost always a false positive. Commercial virus scanning programs are often confused by the structure of Go binaries, which they don't see as often as those compiled from other languages.
> 
> If you've just installed the Go distribution and the system reports it is infected, that's certainly a mistake. To be really thorough, you can verify the download by comparing the checksum with those on the [downloads page](https://go.dev/dl/).
> 
> In any case, if you believe the report is in error, please report a bug to the supplier of your virus scanner. Maybe in time virus scanners can learn to understand Go programs.
