### ISSUE TITLE
AUR packages

### ISSUE THREAD

**Issue by Amolith** [agejevasv/goradion#2]
I created two AUR packages for goradion so Arch Linux users can install it with their preferred AUR helper. You're welcome to link to them in the README if you'd like :)
- [`goradion`](https://aur.archlinux.org/packages/goradion)
- [`goradion-bin`](https://aur.archlinux.org/packages/goradion-bin)

**Comment by agejevasv** [comment]
Awesome, thank you, Amolith! Added to the setup section.
