### ISSUE TITLE
Maybe also the bitrate information?

### ISSUE THREAD

**Issue by 097115** [agejevasv/goradion#3]
Would be great to have some bitrate info alongside the volume, what do you think?  But `mpv ` doesn't seem to handle the `icy-bitrate` tag, so that's probably not exactly easy?

The other way could be adding something like `--term-status-msg='Bitrate: ${audio-bitrate}'` to the `mpv` call, and parsing it, but, again, probably too much fuss?

Thanks for `goradion` anyway! Really nice and handy little gem :)

**Comment by agejevasv** [comment]
Hey, love the suggestion, will add it with the next update, thanks!

**Comment by agejevasv** [comment]
Added in `v0.3.7`: https://github.com/agejevasv/goradion/releases/tag/v0.3.7.

**Comment by agejevasv** [comment]
Added in v0.3.7: https://github.com/agejevasv/goradion/releases/tag/v0.3.7.

**Comment by 097115** [comment]
@agejevasv 

Just wanted to say thanks :) 

Works great!
