### ISSUE TITLE
[REQ] Roadmap

### ISSUE THREAD

**Issue by xxxserxxx** [agejevasv/goradion#5]
Could you jot down the sorts of things you're interested in doing? IME, I've too often submitted patches for features that upstream is not interested in, which results in me having to maintain forks for just the stuff I want indefinitely. It's good to have an idea about whether upstream is willing to accept new features. I could ask about each one before working on it, but even better is knowing where you see the project going.

In particular, I'd like:

- Tags/categories. I see this as another column in the CSV, a space or semicolon separated list of categories. There would also be UI changes for grouping stations by categories, or filtering by category. I'm often in the mood for a _kind_ of music, and being able to filter on tags and show only stations playing those kinds of music is really helpful. Like Genres, but less constrained.
- mpris support. This greatly facilitates integrating a music player in dozens of control/display tools: status bar controllers; dunst messaging, and controling with physical devices like knobs.

I think that's all I'm missing from goradion for now, but it's an example. Some require a fair bit of effort, so it'd be nice to know whether you're amenable to accepting large-ish patches to add support (tags are probably minor; mpris tends to be heavier)

**Comment by agejevasv** [comment]
Honestly I don't have any roadmap, I'm quite content with the current features.

Regarding your suggestions I find tags quite interesting and may implement them in near future.
mpris - I'm not interested; goradion is also used on Macs and Windows PCs and I don't find the value it would add worthwhile. I prefer to keep it small and simple.

**Comment by agejevasv** [comment]
@xxxserxxx I have implemented tags, it doesn't have all the UI changes you have described, but is workable: https://github.com/agejevasv/goradion/releases/tag/v0.4.0

Thank you!

**Comment by xxxserxxx** [comment]
Thank you, and that answers my question. I've been thinking about ways of implementing mpris outside of goradion, but it'd require some way of externally controlling goradion via an API. Like herbstclient for herbstluft, or i3-msg for i3, or... something like that.

I've implemented mpris for a couple of different projects, and it's a burden, I agree. dbus is a PITA to work with, at best; I can see why you might not want it in goradion. Have you considered a more simple soluton, such as an open port that accepts and executes basic commands? Ironically, mpv is already controllable via mpris, so that's covered; it's just the ability to select/change stations that's outside of mpv's control.
